### PR TITLE
(Re)implement ExecutionController, VmController and ExecutionRoutes

### PR DESCRIPTION
**Pull request by sorsaffari**
## What is the goal of this PR?

To use Typescript and move out part of controller and route logic out of `server.ts`

## What are the changes implemented in this PR?

Files to be reviewed are:
- `src/controllers/execution/index.ts`
- `src/controllers/vm/index.ts`
- `src/controllers/vm/scripts/benchmark.sh`
- `src/controllers/vm/scripts/zipkin.sh`
- `src/routes/execution.ts`
- `config.ts`
- `types.ts` > to contain the rest of types and interfaces that may be used _anywhere_.
- `package.ts` > scripts to copy non-`ts` files to `dist/` should be replaced by the appropriate gulp tasks

### CODE REVIEW

**Comment by sorsaffari** [comment]
@marco-scoppetta there is no option for the TS compiler to clean the `outDir` (i.e. `dist` in our case). The issue has been raised and dismissed here: https://github.com/Microsoft/TypeScript/issues/13722

**Comment by sorsaffari** [comment]
@marco-scoppetta 
could you please review:
- [add appRoot and logDir to config](https://github.com/graknlabs/benchmark/pull/276/commits/cfcdc1b6a542d330cc594851f10b6652058b7ab8): decided not to use the `app-root-path` and instead set the app's root relative to the config file
- [improve reliability of starting a vm instance](https://github.com/graknlabs/benchmark/pull/276/commits/3911929785ef43cc2e6c1bfd980b3453667555b0): it turned out even with the `setTimeout` approach, the ssh connection wasn't made to the executor instance reliably and consistently at every attempt. so took a different approach and added some logic to the `start` method of the `VMController` to ping the instance until it becomes available.

**Comment by marco-scoppetta** [comment]
@sorsaffari it looks good to me!

Only question I have is why is esClient.ping commented out? 
Probably a leftover from a work in progress.

**Comment by sorsaffari** [comment]
@marco-scoppetta for some reason (that I haven't investigated yet) it's causing a false negative and so shuts down the server. I'll get to the bottom of it when I get to refactor `server.ts`

**Pull request merged**
